debug: false
exclude-staff: true

database:
  host: localhost
  port: 3306
  name: rankpoints
  username: root
  password: changeMe

placeholder:
  enabled: true
  identifier: rankpoints
  cache-seconds: 10